FROM synesthesiam/opentts

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 8080
ENV PORT=8080
ENV PATH="/usr/bin:${PATH}"
WORKDIR /home/opentts/app
ENTRYPOINT ["sh", "-c", "ffmpeg -version && .venv/bin/python3 app.py --host 0.0.0.0 --port $PORT"]
